apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
  labels:
    app: my-react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
        - name: my-react-app
          image: automationcrgus.azurecr.io/automation-image:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "https://my-aks-cluster-7pd3yyuw.hcp.eastus.azmk8s.io"  # Replace with your API URL
