#runtime as the base image
FROM alpine:3.18

# Variables
ARG NEXT_PUBLIC_APIKEY
ARG NEXT_PUBLIC_AUTHDOMAIN
ARG NEXT_PUBLIC_PROJECTID
ARG NEXT_PUBLIC_STORAGEBUCKET
ARG NEXT_PUBLIC_MESSAGINGSENDERID
ARG NEXT_PUBLIC_APPID
ARG NEXT_PUBLIC_MEASUREMENTID
ARG NEXT_PUBLIC_DATABASE_URL

ENV NEXT_PUBLIC_APIKEY=$NEXT_PUBLIC_APIKEY
ENV NEXT_PUBLIC_AUTHDOMAIN=$NEXT_PUBLIC_AUTHDOMAIN
ENV NEXT_PUBLIC_PROJECTID=$NEXT_PUBLIC_PROJECTID
ENV NEXT_PUBLIC_STORAGEBUCKET=$NEXT_PUBLIC_STORAGEBUCKET
ENV NEXT_PUBLIC_MESSAGINGSENDERID=$NEXT_PUBLIC_MESSAGINGSENDERID
ENV NEXT_PUBLIC_APPID=$NEXT_PUBLIC_APPID
ENV NEXT_PUBLIC_MEASUREMENTID=$NEXT_PUBLIC_MEASUREMENTID
ENV NEXT_PUBLIC_DATABASE_URL=$NEXT_PUBLIC_DATABASE_URL

# Node version
ENV NODE_VERSION 18.0.0

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Set Yarn version
ENV YARN_VERSION 1.22.19

# Install Yarn
RUN apk add --no-cache yarn=${YARN_VERSION}-r0

#Install app dependencies
RUN yarn install

# Copy the app source code to the container
COPY . .

# Build the React app for production
RUN yarn build

# Expose the desired port
EXPOSE 3000

# Start app
CMD ["yarn", "start"]
