# Default values for my-nextjs-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: pipelinegusccr.azurecr.io/my-nextjs-app
  tag: latest

# Add other values here as needed.
