apiVersion: apps/v1
kind: Deployment
metadata:
  name: vega-real-estate-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vega-real-estate-app
  template:
    metadata:
      labels:
        app: vega-real-estate-app
    spec:
       containers:
        - name: vega-real-estate-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"