apiVersion: v1
kind: Service
metadata:
  name: vega-real-estate-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    app: vega-real-estate-app
