apiVersion: v1
kind: Service
metadata:
  name: my-nextjs-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: my-nextjs-app
