name: Next.js App Deployment

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.0.0

      - name: Install dependencies
        run: yarn install

      - name: Build Next.js app
        run: yarn build

      - name: Install AZ CLI
        uses: elstudio/action-install-azure-cli@v1

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Log in to Azure Container Registry
        run: az acr login --name pipelinegusccr

      - name: Build and tag Docker image
        run: |
          docker build -t pipelinegusccr.azurecr.io/my-nextjs-app:${{ github.sha }} .
          docker push pipelinegusccr.azurecr.io/my-nextjs-app:${{ github.sha }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.4

      - name: Current location
        run: |
          ls -la

      - name: Terraform Init
        run: terraform init

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Get AKS Cluster Info
        run: |
          az aks get-credentials --resource-group pipeline --name my-aks-cluster
          kubectl config view --minify --raw

      - name: Print AKS Cluster Info
        run: cat $HOME/.kube/config

      - name: Current location
        run: |
          ls -la

      - name: Deploy with Helm
        run: |
          helm upgrade --install my-nextjs-app . \
            --set image.tag=${{ github.sha }}

      - name: Wait for deployment to finish
        run: |
          kubectl rollout status deployment/my-nextjs-app
