name: Simple Workflow

on:
  push:
    branches:
      - '*'

jobs:
  simple_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print a message
      run: echo "Hello, this is a simple GitHub Actions workflow!"
