name: Simple Workflow

on:
  push:
    branches:
      - '*'

jobs:
  simple_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print a message
      run: echo "Hello, this is a simple GitHub Actions workflow!"

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Python Script
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        echo: |
          echo 'TESTING'

    - name: Execute Python Script
      run: |
        python -c "print('Hello from the Python script!')"
