name: Check Author on Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check-author:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get pull request author
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
        run: |
          PR_AUTHOR=$(gh pr view ${{ github.event.number }} --json author.login -q .author.login)
          echo "Pull request author: $PR_AUTHOR"

      - name: Check author login
        run: |
          if [ "$PR_AUTHOR" == "gusvega" ]; then
            PR_NUMBER=$(gh pr view ${{ github.event.number }} --json number -q .number)
            echo "Pull request number: $PR_NUMBER"
          else
            echo "Author is not gusvega. Skipping further actions."
          fi

