name: Timestamped Workflow

on:
  push:
    branches:
      - '*'

jobs:
  timestamped_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display Current Time
      run: |
        echo "Current time: $(date +"%T")"

    - name: Setup Python and Display Time
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
      run: |
        echo "Python setup complete at $(date +"%T")"

    - name: Execute Python Script and Display Time
      run: |
        echo "Executing Python script at $(date +"%T")"
        python -c "print('Hello from the Python script!')"
