name: Check Author on Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check-author:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get pull request author and number
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_INFO=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.number }} --json user.login,number)
          PR_AUTHOR=$(echo "$PR_INFO" | jq -r '.user.login')
          PR_NUMBER=$(echo "$PR_INFO" | jq -r '.number')

          if [ "$PR_AUTHOR" == "gusvega" ]; then
            echo "Pull request author: $PR_AUTHOR"
            echo "Pull request number: $PR_NUMBER"
          else
            echo "Author is not gusvega. Skipping further actions."
          fi
