name: Variable Workflow

on:
  workflow_dispatch: # This allows the workflow to be triggered manually from the Actions tab

jobs:
  set-variables:
    runs-on: ubuntu-latest

    outputs:
      VAR1: ${{ steps.set-vars.outputs.VAR1 }}
      VAR2: ${{ steps.set-vars.outputs.VAR2 }}

    steps:
      - name: Set Variables
        id: set-vars
        run: |
          echo "VAR1=value1"
          echo "VAR2=value2"
          echo "::set-output name=VAR1::value1"
          echo "::set-output name=VAR2::value2"

  read-variables:
    needs: set-variables
    runs-on: ubuntu-latest

    steps:
      - name: Read Variables
        run: |
          echo "VAR1 is ${{ needs.set-variables.outputs.VAR1 }}"
          echo "VAR2 is ${{ needs.set-variables.outputs.VAR2 }}"
